
all:
	mkdir -p ../build/drivers
	@$(MAKE) -C keyboard
	@$(MAKE) -C cga
	@$(MAKE) -C mbspeaker
	@$(MAKE) -C pci

clean:
	@$(MAKE) -C keyboard clean
	@$(MAKE) -C cga clean
	@$(MAKE) -C mbspeaker clean
	@$(MAKE) -C pci clean


