
all:
	@$(MAKE) -C test
	@$(MAKE) -C ultrashell
	@$(MAKE) -C ls
	@$(MAKE) -C lscpu
	@$(MAKE) -C cat
	@$(MAKE) -C cp

clean:
	@$(MAKE) -C test clean
	@$(MAKE) -C ultrashell clean
	@$(MAKE) -C ls clean
	@$(MAKE) -C lscpu clean
	@$(MAKE) -C cat clean
	@$(MAKE) -C cp clean

